### PR TITLE
fix: do not change entity title if not a ref (#263)

### LINKED ISSUE #263: For catalog entity names with slash (/) only last part is shown in attachment control
When trying to attach a question to a catalog entity where the name contains a slash (/) only the part after the slash of the name shows up in the selection control.

Image

When viewing the question the full name is displayed.

Image

### PR DESCRIPTION
**Pull request by nebulon42**
Fixes #263

### CODE REVIEW

File: plugins/qeta-react/src/utils/utils.ts [hunk 1]
```diff
@@ -49,7 +49,7 @@ export const formatEntityName = (username?: string) => {
 
 export const getEntityTitle = (entity: Entity): string => {
   const stringified = stringifyEntityRef(entity);
-  return formatEntityName(entity.metadata.title ?? stringified) ?? stringified;
+  return entity.metadata.title ?? formatEntityName(stringified) ?? stringified;
```
Comment (drodil) [inline plugins/qeta-react/src/utils/utils.ts:52]: I think we should change this whole function to use `entityPresentationApi`. But that is a bigger refactor I am afraid so let's go with this for now.

**Review by drodil — APPROVED** [review]
